//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsMediaCreator.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsMediaCreator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Based on:.
        /// </summary>
        internal static string BasedOn {
            get {
                return ResourceManager.GetString("BasedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string btnAbout {
            get {
                return ResourceManager.GetString("btnAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Close.
        /// </summary>
        internal static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        internal static string btnCancel2 {
            get {
                return ResourceManager.GetString("btnCancel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Download select.
        /// </summary>
        internal static string btnDownload {
            get {
                return ResourceManager.GetString("btnDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Help me choose.
        /// </summary>
        internal static string btnHelp {
            get {
                return ResourceManager.GetString("btnHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string btnLang {
            get {
                return ResourceManager.GetString("btnLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pause.
        /// </summary>
        internal static string btnPause {
            get {
                return ResourceManager.GetString("btnPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Build:.
        /// </summary>
        internal static string build {
            get {
                return ResourceManager.GetString("build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  complete.
        /// </summary>
        internal static string complete {
            get {
                return ResourceManager.GetString("complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Developed by: KrDev.
        /// </summary>
        internal static string DevBy {
            get {
                return ResourceManager.GetString("DevBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  contact information.
        /// </summary>
        internal static string devInformation {
            get {
                return ResourceManager.GetString("devInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Developed for educational purposes, the isos images provided are not the property of KrDev.
        /// </summary>
        internal static string Disclaimer {
            get {
                return ResourceManager.GetString("Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Download :  Windows Media Creator.
        /// </summary>
        internal static string downloaderTitle {
            get {
                return ResourceManager.GetString("downloaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Download path: .
        /// </summary>
        internal static string downPatch {
            get {
                return ResourceManager.GetString("downPatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ISO Files|*.iso.
        /// </summary>
        internal static string filter {
            get {
                return ResourceManager.GetString("filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Creator.
        /// </summary>
        internal static string lblCreator {
            get {
                return ResourceManager.GetString("lblCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Downloaded:.
        /// </summary>
        internal static string lblDown {
            get {
                return ResourceManager.GetString("lblDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Download speed: .
        /// </summary>
        internal static string lblDownSpeed {
            get {
                return ResourceManager.GetString("lblDownSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filter:.
        /// </summary>
        internal static string lblFiltro {
            get {
                return ResourceManager.GetString("lblFiltro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Obtaining information, this process should not take long....
        /// </summary>
        internal static string lblInfo {
            get {
                return ResourceManager.GetString("lblInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Media.
        /// </summary>
        internal static string lblMedia {
            get {
                return ResourceManager.GetString("lblMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search by:.
        /// </summary>
        internal static string lblSearch {
            get {
                return ResourceManager.GetString("lblSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Windows ISO catalog.
        /// </summary>
        internal static string lblTitulo {
            get {
                return ResourceManager.GetString("lblTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Windows.
        /// </summary>
        internal static string lblWindows {
            get {
                return ResourceManager.GetString("lblWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Based on: .
        /// </summary>
        internal static string lblwinver {
            get {
                return ResourceManager.GetString("lblwinver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap linkTree {
            get {
                object obj = ResourceManager.GetObject("linkTree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edition.
        /// </summary>
        internal static string listViewArchivos_Column1 {
            get {
                return ResourceManager.GetString("listViewArchivos_Column1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Architecture.
        /// </summary>
        internal static string listViewArchivos_Column3 {
            get {
                return ResourceManager.GetString("listViewArchivos_Column3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Catalog : Windows Media Creator.
        /// </summary>
        internal static string MainForm {
            get {
                return ResourceManager.GetString("MainForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap miniOS {
            get {
                object obj = ResourceManager.GetObject("miniOS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a English.
        /// </summary>
        internal static string mnuEnglish {
            get {
                return ResourceManager.GetString("mnuEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spanish.
        /// </summary>
        internal static string mnuSpanish {
            get {
                return ResourceManager.GetString("mnuSpanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modified by: .
        /// </summary>
        internal static string ModBy {
            get {
                return ResourceManager.GetString("ModBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Size.
        /// </summary>
        internal static string ModSize {
            get {
                return ResourceManager.GetString("ModSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Version.
        /// </summary>
        internal static string ModVersion {
            get {
                return ResourceManager.GetString("ModVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to cancel the download and return to the catalog?
        ///
        ///Press &apos;Yes&apos; to cancel and return to the ISO catalog
        ///
        ///Press &apos;No&apos; to cancel and exit.
        /// </summary>
        internal static string msgCancelExit {
            get {
                return ResourceManager.GetString("msgCancelExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to exit the application? all download progress will be lost.
        /// </summary>
        internal static string msgTitleDownload {
            get {
                return ResourceManager.GetString("msgTitleDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Do you wish to continue?.
        /// </summary>
        internal static string msgTitleDownload2 {
            get {
                return ResourceManager.GetString("msgTitleDownload2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No suitable operating system found in the list.
        /// </summary>
        internal static string noOp {
            get {
                return ResourceManager.GetString("noOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ntdev {
            get {
                object obj = ResourceManager.GetObject("ntdev", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operating System: .
        /// </summary>
        internal static string operatingS {
            get {
                return ResourceManager.GetString("operatingS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Processor: .
        /// </summary>
        internal static string Processor {
            get {
                return ResourceManager.GetString("Processor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a General.
        /// </summary>
        internal static string rdGeneral {
            get {
                return ResourceManager.GetString("rdGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Windows 10.
        /// </summary>
        internal static string rdWin10 {
            get {
                return ResourceManager.GetString("rdWin10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Windows 11.
        /// </summary>
        internal static string rdWin11 {
            get {
                return ResourceManager.GetString("rdWin11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resumen.
        /// </summary>
        internal static string Resumen {
            get {
                return ResourceManager.GetString("Resumen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recommended operating system: .
        /// </summary>
        internal static string rOp {
            get {
                return ResourceManager.GetString("rOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save file.
        /// </summary>
        internal static string saveFile {
            get {
                return ResourceManager.GetString("saveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error connecting to the server.
        /// </summary>
        internal static string serverError {
            get {
                return ResourceManager.GetString("serverError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sfdx {
            get {
                object obj = ResourceManager.GetObject("sfdx", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a System information.
        /// </summary>
        internal static string SysInfo {
            get {
                return ResourceManager.GetString("SysInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tomex {
            get {
                object obj = ResourceManager.GetObject("tomex", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap winteros {
            get {
                object obj = ResourceManager.GetObject("winteros", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap x {
            get {
                object obj = ResourceManager.GetObject("x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap xlite {
            get {
                object obj = ResourceManager.GetObject("xlite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ytb {
            get {
                object obj = ResourceManager.GetObject("ytb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
